spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graphqldb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

dgs:
  graphql:
    graphiql:
      enabled: true
    schema-locations: classpath*:graphql/**/*.graphqls
