package imi.jazzberry.server.enums;

public enum ResponseEntityEnum {
    USER_EXIST,
    USER_DOES_NOT_EXIST,
    USER_CONTAINS_BLANK,
    USER_NOT_FOUND,
    USER_INVALID,
    ROLE_EXIST,
    ROLE_DOES_NOT_EXIST,
    OK,
    OLD_PASSWORD_MISMATCH,
    PASSWORD,
    EMAIL,
    EMAIL_INVALID,
    NOT_PICTURE,
    PICTURE,
    LOCATION_CREATED,
    FOLLOWING,
    NOT_FOLLOWING
}
